name: Publish python poetry package
on:
  # Sync pypi releases with releases drafted by release-please
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        shell: bash
        env:
          PYPI_DB_ROCKET: ${{ secrets.PYPI_DB_ROCKET }}
        run: |
          pip install -r requirements.txt
          python3 -m build --no-isolation
          echo "Build successfull, uploading now..."
          python3 -m twine upload dist/* -u "__token__" -p "$PYPI_DB_ROCKET" --skip-existing
          echo "Upload successfull!"